package student.servlet;

import java.io.IOException;
import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

import javax.servlet.ServletException;
/*import javax.servlet.annotation.WebServlet;*/
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

/**
 * Servlet implementation class Studentservlet
 */
/*@WebServlet("/Studentservlet")*/
public class Studentservlet extends HttpServlet {
	private static final long serialVersionUID = 1L;
       
    /**
     * @see HttpServlet#HttpServlet()
     */
    public Studentservlet() {
        super();
        // TODO Auto-generated constructor stub
    }

	/**
	 * @see HttpServlet#doGet(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub
		response.getWriter().append("Served at: ").append(request.getContextPath());
	}

	/**
	 * @see HttpServlet#doPost(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		/*// TODO Auto-generated method stub
		doGet(request, response);*/
		

response.setContentType("text/html");  
PrintWriter out = response.getWriter();  
 int i=0;        
int n=Integer.parseInt(request.getParameter("m1"));
int p=Integer.parseInt(request.getParameter("m2"));
int e=Integer.parseInt(request.getParameter("m3"));
int t=Integer.parseInt(request.getParameter("tol"));
int r=Integer.parseInt(request.getParameter("rank"));
          
try{  
Class.forName("oracle.jdbc.driver.OracleDriver");  
Connection con=DriverManager.getConnection(  
"jdbc:oracle:thin:@192.168.10.10:1521/XE","system","rad");  
  
PreparedStatement ps=con.prepareStatement(  
"insert into studenttb values(?,?,?,?,?,?)");  
ResultSet tableKeys = ps.getGeneratedKeys();

tableKeys.next();

int autoGeneratedID = tableKeys.getInt(1);
ps.setInt(1,autoGeneratedID);
ps.setInt(2,n);
ps.setInt(3,p);  
ps.setInt(4,e);  
ps.setInt(5,t); 
ps.setInt(6,r); 
 
          
	i=ps.executeUpdate();  
if(i>0)  
out.print("You are successfully registered...");  
      
          
}catch (Exception e2) {System.out.println(e2);}  
          
out.close(); 	
	}

}
